package com.killer560.hub.auction;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.killer560.hub.util.ModLog;
import org.slf4j.Logger;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

/**
 * The bundled Bazaar product table ({@code assets/killer560smod/bazaar/products.json}): every product's name, the
 * Hypixel Bazaar category and group it sits under, its rarity and a real icon source.
 * <p>
 * Generated by {@code tools/bazaar/gen_bazaar_data.py} (2026-10-07) from Hypixel's own bazaar and item resources, the
 * NotEnoughUpdates item repo (MIT) and the wiki's Bazaar item list. It exists because neither Hypixel resource is
 * enough on its own: 1,174 of the 2,201 products are not in {@code /v2/resources/skyblock/items} at all (every
 * enchantment, every shard, the essences, the faction rabbits), and ~480 of the rest only name a model from
 * Hypixel's resource pack, which draws as paper whenever that pack is not loaded. Products added after the table was
 * generated still work: {@link BazaarIcons} and {@link BazaarApi} fall back to the live item catalog for them.
 */
public final class BazaarCatalog {

    private static final Logger LOGGER = ModLog.get("killer560smod-bazaar");
    private static final String PATH = "/assets/killer560smod/bazaar/products.json";

    /** One product's row. {@code skinHash} is the texture id on textures.minecraft.net; {@code vanillaId} a modern
     *  item id; {@code legacy} a 1.8 {@code minecraft:name:damage} pushed through vanilla's flattening fix;
     *  {@code packModel} Hypixel's resource-pack model, used only when that model is actually loaded. */
    public record Entry(String productId, String name, int group, String tier, String skinHash, String vanillaId,
            String legacy, String packModel, boolean glint, boolean ultimate) {
    }

    /** A Bazaar category ("Farming") and one of its groups ("Wheat &amp; Seeds"). */
    public record Group(String category, String name) {
    }

    private static volatile boolean loaded;
    private static Map<String, Entry> byId = Map.of();
    private static Map<String, String> idByName = Map.of();
    private static List<Group> groups = List.of();
    private static List<String> categories = List.of();

    private BazaarCatalog() {
    }

    /** Loads the table once. About 280 KB of JSON; callers on the render thread should prefer {@link #isLoaded}. */
    public static synchronized void ensureLoaded() {
        if (loaded) {
            return;
        }
        try (InputStream in = BazaarCatalog.class.getResourceAsStream(PATH)) {
            if (in != null) {
                parse(JsonParser.parseReader(new InputStreamReader(in, StandardCharsets.UTF_8)).getAsJsonObject());
            } else {
                LOGGER.warn("[Bazaar] bundled product table missing ({})", PATH);
            }
        } catch (Exception e) {
            LOGGER.warn("[Bazaar] bundled product table unreadable", e);
        }
        loaded = true;
    }

    public static boolean isLoaded() {
        return loaded;
    }

    private static void parse(JsonObject root) {
        List<Group> g = new ArrayList<>();
        List<String> cats = new ArrayList<>();
        for (JsonElement el : root.getAsJsonArray("groups")) {
            JsonObject o = el.getAsJsonObject();
            Group group = new Group(o.get("c").getAsString(), o.get("g").getAsString());
            g.add(group);
            if (!cats.contains(group.category())) {
                cats.add(group.category());
            }
        }
        Map<String, Entry> ids = new HashMap<>();
        Map<String, String> names = new HashMap<>();
        // Sorted, so when two products share a name (three legacy pairs do) the same one wins every time.
        List<Map.Entry<String, JsonElement>> rows = new ArrayList<>(root.getAsJsonObject("products").entrySet());
        rows.sort(Map.Entry.comparingByKey());
        for (Map.Entry<String, JsonElement> e : rows) {
            JsonObject o = e.getValue().getAsJsonObject();
            Entry entry = new Entry(e.getKey(), str(o, "n"), o.has("g") ? o.get("g").getAsInt() : g.size() - 1,
                    str(o, "t"), str(o, "s"), str(o, "i"), str(o, "l"), str(o, "m"),
                    o.has("e"), o.has("u"));
            ids.put(entry.productId(), entry);
            if (entry.name() != null) {
                names.putIfAbsent(entry.name().toLowerCase(Locale.ROOT), entry.productId());
            }
        }
        byId = Collections.unmodifiableMap(ids);
        idByName = Collections.unmodifiableMap(names);
        groups = List.copyOf(g);
        categories = List.copyOf(cats);
    }

    private static String str(JsonObject o, String key) {
        return o.has(key) && !o.get(key).isJsonNull() ? o.get(key).getAsString() : null;
    }

    public static Entry get(String productId) {
        ensureLoaded();
        return productId == null ? null : byId.get(productId);
    }

    /** The product a Hypixel menu calls {@code name} (colour codes already stripped), or null. */
    public static String idForName(String name) {
        ensureLoaded();
        return name == null ? null : idByName.get(name.trim().toLowerCase(Locale.ROOT));
    }

    public static Set<String> ids() {
        ensureLoaded();
        return byId.keySet();
    }

    public static List<Group> groups() {
        ensureLoaded();
        return groups;
    }

    /** Category names in Hypixel's menu order (Farming, Mining, Combat, Woods &amp; Fishes, Oddities). */
    public static List<String> categories() {
        ensureLoaded();
        return categories;
    }

    /** Group names of {@code category}, in menu order, each with its index into {@link #groups()}. */
    public static Map<Integer, String> groupsOf(String category) {
        Map<Integer, String> out = new LinkedHashMap<>();
        List<Group> all = groups();
        for (int i = 0; i < all.size(); i++) {
            if (all.get(i).category().equals(category)) {
                out.put(i, all.get(i).name());
            }
        }
        return out;
    }

    public static Group group(int index) {
        List<Group> all = groups();
        return index >= 0 && index < all.size() ? all.get(index) : null;
    }
}
