package com.killer560.hub.packdisabler;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.killer560.hub.profileviewer.item.LegacyItems;
import com.killer560.hub.util.ModLog;
import net.minecraft.core.component.DataComponents;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.Identifier;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.component.ResolvableProfile;
import org.slf4j.Logger;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;

/**
 * What every SkyBlock item looked like BEFORE Hypixel's 2026 resource pack: the one table both Pack Disabler and the
 * Bazaar browser's icons read ({@code assets/killer560smod/skyblock/item_looks.json}, generated by
 * {@code tools/items/gen_item_looks.py} from Hypixel's item resource and NotEnoughUpdates' repo before and after its
 * resource-pack conversion; about 3,000 rows: every Bazaar product and every item Hypixel moved onto a pack model).
 * <p>
 * Every look names a VANILLA thing resolved at runtime - an item id, a 1.8 id + damage through vanilla's own flattening
 * fix, or a player-head texture through the normal player-head path - so the player's own resource packs draw it (his
 * Faithful seeds stay Faithful seeds). Items that never had a look of their own get our original textures, which are
 * ordinary assets at {@code killer560smod:packdisabler/<id>}, so a selected resource pack can replace those too.
 */
public final class ItemLooks {

    private static final Logger LOGGER = ModLog.get("killer560smod-packdisabler");
    private static final String PATH = "/assets/killer560smod/skyblock/item_looks.json";
    public static final String OWN_NAMESPACE = "killer560smod";
    private static final Identifier PLAYER_HEAD_MODEL = Identifier.fromNamespaceAndPath("minecraft", "player_head");

    /** One row. {@code ownTexture} is the key of our own texture, used only when the row has no vanilla look. */
    public record Look(String skinHash, String vanillaId, String legacy, String packModel, boolean glint,
            String ownTexture) {
        public boolean hasVanillaLook() {
            return skinHash != null || vanillaId != null
                    || legacy != null && !legacy.startsWith("minecraft:paper") && !legacy.startsWith("minecraft:skull");
        }

        public boolean hasAnyLook() {
            return hasVanillaLook() || ownTexture != null;
        }
    }

    private static volatile boolean loaded;
    private static Map<String, Look> rows = Map.of();
    private static final Map<String, Optional<Identifier>> MODEL_CACHE = new ConcurrentHashMap<>();
    private static final Map<String, Optional<ResolvableProfile>> PROFILE_CACHE = new ConcurrentHashMap<>();

    private ItemLooks() {
    }

    /** Loads the table once (~290 KB). The render path calls {@link #get} only after {@link #isLoaded}. */
    public static synchronized void ensureLoaded() {
        if (loaded) {
            return;
        }
        try (InputStream in = ItemLooks.class.getResourceAsStream(PATH)) {
            if (in == null) {
                LOGGER.warn("[Pack Disabler] item table missing ({})", PATH);
            } else {
                JsonObject items = JsonParser.parseReader(new InputStreamReader(in, StandardCharsets.UTF_8))
                        .getAsJsonObject().getAsJsonObject("items");
                Map<String, Look> map = new HashMap<>(items.size() * 2);
                for (Map.Entry<String, JsonElement> e : items.entrySet()) {
                    JsonObject o = e.getValue().getAsJsonObject();
                    map.put(e.getKey(), new Look(str(o, "s"), str(o, "i"), str(o, "l"), str(o, "m"), o.has("e"),
                            str(o, "o")));
                }
                rows = Collections.unmodifiableMap(map);
            }
        } catch (Exception e) {
            LOGGER.warn("[Pack Disabler] item table unreadable", e);
        }
        loaded = true;
    }

    public static boolean isLoaded() {
        return loaded;
    }

    private static String str(JsonObject o, String key) {
        return o.has(key) && !o.get(key).isJsonNull() ? o.get(key).getAsString() : null;
    }

    /** The row for a SkyBlock id ({@code "INK_SACK:3"} or NEU's {@code "INK_SACK-3"}), or null. */
    public static Look get(String skyblockId) {
        if (skyblockId == null || skyblockId.isEmpty()) {
            return null;
        }
        ensureLoaded();
        Look look = rows.get(skyblockId);
        if (look == null && skyblockId.indexOf('-') >= 0) {
            look = rows.get(skyblockId.replace('-', ':'));
        }
        return look;
    }

    public static int size() {
        ensureLoaded();
        return rows.size();
    }

    /** Our own texture's item model id: {@code killer560smod:packdisabler/<key>}. */
    public static Identifier ownModel(String key) {
        return Identifier.fromNamespaceAndPath(OWN_NAMESPACE, "packdisabler/" + key);
    }

    /** The vanilla item a look names (null for a head, our texture, or nothing known). */
    public static Item vanillaItem(Look look) {
        if (look == null) {
            return null;
        }
        if (look.vanillaId() != null) {
            Identifier id = Identifier.tryParse("minecraft:" + look.vanillaId());
            Item item = id == null ? null : BuiltInRegistries.ITEM.getOptional(id).orElse(null);
            if (item != null && item != Items.AIR) {
                return item;
            }
        }
        if (look.legacy() != null) {
            int colon = look.legacy().lastIndexOf(':');
            String name = colon > 0 ? look.legacy().substring(0, colon) : look.legacy();
            int damage = 0;
            try {
                damage = colon > 0 ? Integer.parseInt(look.legacy().substring(colon + 1)) : 0;
            } catch (NumberFormatException ignored) {
            }
            Item item = LegacyItems.legacyItem(name, damage);
            if (item != null && item != Items.PAPER && item != Items.PLAYER_HEAD) {
                return item;
            }
        }
        return null;
    }

    /**
     * The item model to draw {@code skyblockId} with, or null when the table knows no look for it. For a vanilla look
     * this is that item's OWN default model id ({@code minecraft:wheat_seeds}), so whatever resource pack the player
     * runs decides the pixels; for a head it is the vanilla player-head model, with {@link #profileFor} supplying the
     * skin. Cached per id; never throws.
     */
    public static Identifier modelFor(String skyblockId) {
        if (skyblockId == null) {
            return null;
        }
        Optional<Identifier> cached = MODEL_CACHE.get(skyblockId);
        if (cached != null) {
            return cached.orElse(null);
        }
        Identifier model = null;
        try {
            Look look = get(skyblockId);
            if (look != null) {
                if (look.skinHash() != null) {
                    model = PLAYER_HEAD_MODEL;
                } else {
                    Item item = vanillaItem(look);
                    if (item != null) {
                        model = item.components().get(DataComponents.ITEM_MODEL);
                    } else if (look.ownTexture() != null) {
                        model = ownModel(look.ownTexture());
                    }
                }
            }
        } catch (Exception e) {
            model = null;
        }
        MODEL_CACHE.put(skyblockId, Optional.ofNullable(model));
        return model;
    }

    /** The pre-pack head skin of {@code skyblockId}, or null when its old look was not a head. */
    public static ResolvableProfile profileFor(String skyblockId) {
        if (skyblockId == null) {
            return null;
        }
        Optional<ResolvableProfile> cached = PROFILE_CACHE.get(skyblockId);
        if (cached != null) {
            return cached.orElse(null);
        }
        ResolvableProfile profile = null;
        try {
            Look look = get(skyblockId);
            if (look != null && look.skinHash() != null) {
                profile = LegacyItems.skullProfile(textureValue(look.skinHash()));
            }
        } catch (Exception e) {
            profile = null;
        }
        PROFILE_CACHE.put(skyblockId, Optional.ofNullable(profile));
        return profile;
    }

    /**
     * Gives {@code stack} the pre-pack look of {@code skyblockId} as components (item model, plus the skin for a head),
     * leaving its item type alone: the vanilla player-head model reads the PROFILE component off any stack. Returns
     * false, changing nothing, when the table knows no look. For stacks the mod BUILDS (profile viewer, browsers);
     * stacks from the server are handled at draw time by the item-model mixin instead.
     */
    public static boolean applyLook(ItemStack stack, String skyblockId) {
        try {
            Identifier model = modelFor(skyblockId);
            if (stack == null || stack.isEmpty() || model == null) {
                return false;
            }
            stack.set(DataComponents.ITEM_MODEL, model);
            ResolvableProfile profile = profileFor(skyblockId);
            if (profile != null) {
                stack.set(DataComponents.PROFILE, profile);
            }
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    /** The base64 "textures" property value for a textures.minecraft.net hash. */
    public static String textureValue(String skinHash) {
        String json = "{\"textures\":{\"SKIN\":{\"url\":\"http://textures.minecraft.net/texture/" + skinHash + "\"}}}";
        return Base64.getEncoder().encodeToString(json.getBytes(StandardCharsets.UTF_8));
    }
}
